# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drYpuYVeoiNyYXAPmL-gaOHqyI_dEJvj
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import plotly.express as px

@st.cache_resource
def load_model():
    with open('model/fraud_model.pkl', 'rb') as f:
        return pickle.load(f)

model = load_model()
df = pd.read_csv('creditcard.csv')

st.title("🔍 Credit Card Fraud Detection")
st.markdown("---")

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Total Transactions", "284,807")
with col2:
    st.metric("Fraud Cases", "492")
with col3:
    st.metric("Fraud %", "0.17%")

st.markdown("---")

st.subheader("🎯 Test Random Transaction")
if st.button("Check Random Transaction"):
    row = df.sample(1).iloc[0]
    features = row.drop(['Class', 'Time']).values.reshape(1, -1)
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][1]
    actual = row['Class']

    if prediction == 1:
        st.error(f"🚨 FRAUD DETECTED! Confidence: {probability:.2%}")
    else:
        st.success(f"✅ Legitimate! Confidence: {1-probability:.2%}")
    st.info(f"Actual: {'Fraud' if actual==1 else 'Legitimate'}")

st.markdown("---")
fig = px.pie(
    values=df['Class'].value_counts().values,
    names=['Legitimate', 'Fraud'],
    color_discrete_sequence=['#00CC96', '#EF553B']
)
st.plotly_chart(fig, use_container_width=True)