# -*- coding: utf-8 -*-
"""creditcard.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drYpuYVeoiNyYXAPmL-gaOHqyI_dEJvj
"""

# Kaggle csv file
import kaggle
kaggle.api.dataset_download_files(
    'mlg-ulb/creditcardfrauddetection',
    path='.',
    unzip=True
)

