# -*- coding: utf-8 -*-
"""credit card train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drYpuYVeoiNyYXAPmL-gaOHqyI_dEJvj
"""

# python
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from xgboost import XGBClassifier
import pickle
import os

df = pd.read_csv("creditcard.csv")

X = df.drop(['Class','Time'], axis=1)
y = df['Class']

scaler = StandardScaler()
X['Amount'] = scaler.fit_transform(X[['Amount']])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=len(y_train[y_train==0])/len(y_train[y_train==1]),
    random_state=42)

xgb_model.fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)
print(classification_report(y_test, y_pred))

os.makedirs('model', exist_ok=True)
with open('fraud_model.pkl', 'wb') as f:
    pickle.dump(xgb_model, f)

